// examples/nuxt-embedded/app/pages/dashboard.vue
<script setup lang="ts">
const { data: session } = await useFetch("/api/session");
if (!session.value) {
  await navigateTo("/");
}

const { data: providers } = await useFetch("/api/providers");

const providerName = computed(
  () => providers.value?.find((p) => p.slug === session.value?.provider)?.name ?? session.value?.provider,
);

const otherProviders = computed(() => providers.value?.filter((p) => p.slug !== session.value?.provider) ?? []);

const initials = computed(() =>
  (session.value?.user.name ?? "?")
    .split(" ")
    .map((n) => n[0])
    .join("")
    .toUpperCase()
    .slice(0, 2),
);
</script>

<template>
  <div v-if="session" class="card">
    <h1>Dashboard</h1>
    <p class="subtitle">
      You're signed in via <span class="badge">{{ providerName }}</span>
    </p>

    <div class="profile">
      <div class="avatar">{{ initials }}</div>
      <div class="profile-text">
        <p class="name">{{ session.user.name }}</p>
        <p v-if="session.user.login" class="muted-line">@{{ session.user.login }}</p>
        <p class="muted-line">{{ session.user.email }}</p>
      </div>
    </div>

    <p class="label">Access Token</p>
    <code class="token">{{ session.accessToken }}</code>

    <a v-for="p in otherProviders" :key="p.slug" class="btn" :href="`/api/auth/${p.slug}`">
      Switch to {{ p.name }}
    </a>

    <form action="/api/auth/signout" method="post">
      <button type="submit" class="btn btn-danger">Sign Out</button>
    </form>
  </div>
</template>

<style scoped>
.badge {
  display: inline-block;
  padding: 0.1rem 0.5rem;
  border-radius: 0.4rem;
  background: #26262f;
  color: var(--fg);
  font-size: 0.8rem;
}

.profile {
  display: flex;
  align-items: center;
  gap: 1rem;
  margin-bottom: 1.5rem;
}

.avatar {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 3.25rem;
  height: 3.25rem;
  border-radius: 999px;
  background: #26262f;
  font-weight: 600;
}

.profile-text {
  min-width: 0;
}

.name {
  margin: 0;
  font-weight: 600;
  font-size: 1.05rem;
}

.muted-line {
  margin: 0.15rem 0 0;
  color: var(--muted);
  font-size: 0.85rem;
}

.label {
  margin: 0 0 0.4rem;
  font-size: 0.8rem;
  font-weight: 500;
  color: var(--muted);
}

.token {
  display: block;
  padding: 0.75rem;
  margin-bottom: 1.25rem;
  border-radius: 0.5rem;
  background: #0b0b0f;
  border: 1px solid var(--border);
  font-size: 0.75rem;
  word-break: break-all;
}

form {
  margin-top: 0.75rem;
}
</style>

// examples/nextjs-embedded/src/app/dashboard/page.tsx
import { redirect } from "next/navigation";
import { getSession } from "@/lib/session";
import { providers } from "@/lib/providers";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { buttonVariants } from "@/components/ui/button-variants";
import { Separator } from "@/components/ui/separator";
import { cn } from "@/lib/utils";

export default async function Dashboard() {
  const session = await getSession();
  if (!session) redirect("/");

  const provider = providers[session.provider];
  const initials = (session.user.name ?? "?")
    .split(" ")
    .map((n) => n[0])
    .join("")
    .toUpperCase()
    .slice(0, 2);

  return (
    <div className="flex flex-1 items-center justify-center p-4">
      <Card className="w-full max-w-md">
        <CardHeader className="text-center">
          <CardTitle className="text-2xl">Dashboard</CardTitle>
          <CardDescription>
            You&apos;re signed in via{" "}
            <Badge variant="secondary">{provider?.name ?? session.provider}</Badge>
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-6">
          <div className="flex items-center gap-4">
            <Avatar className="size-14">
              <AvatarFallback className="text-lg">{initials}</AvatarFallback>
            </Avatar>
            <div className="min-w-0">
              <p className="font-semibold text-lg truncate">
                {session.user.name}
              </p>
              {session.user.login && (
                <p className="text-sm text-muted-foreground truncate">
                  @{session.user.login}
                </p>
              )}
              <p className="text-sm text-muted-foreground truncate">
                {session.user.email}
              </p>
            </div>
          </div>

          <Separator />

          <div className="space-y-2">
            <p className="text-sm font-medium text-muted-foreground">
              Access Token
            </p>
            <code className="block text-xs bg-muted rounded-md p-3 break-all font-mono">
              {session.accessToken}
            </code>
          </div>

          <Separator />

          <div className="flex gap-3">
            {Object.values(providers)
              .filter((p) => p.slug !== session.provider)
              .map((p) => (
                <a
                  key={p.slug}
                  href={`/api/auth/${p.slug}`}
                  className={cn(
                    buttonVariants({ variant: "outline" }),
                    "flex-1"
                  )}
                >
                  Switch to {p.name}
                </a>
              ))}
          </div>

          <form action="/api/auth/signout" method="post">
            <Button variant="destructive" className="w-full">
              Sign Out
            </Button>
          </form>
        </CardContent>
      </Card>
    </div>
  );
}
